<a href="https://colab.research.google.com/github/MiguelUTEC26/etl-data-pipeline-2534562019/blob/main/B_inventario.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [48]:
from sqlalchemy import create_engine
import pandas as pd
url = "https://raw.githubusercontent.com/MiguelUTEC26/etl-data-pipeline-2534562019/refs/heads/main/raw/B_inventario.csv"
df = pd.read_csv(url)

df.head()

  id_inventario id_producto stock      bodega
0         I7000      PR1115   165    Tránsito
1         I7001      PR1031   236  Sucursal 1
2         I7002      PR1129    40  Sucursal 2
3         I7003      PR1083    61     Central
4         I7004      PR1021   245     Central

In [49]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_inventario  186 non-null    object
 1   id_producto    180 non-null    object
 2   stock          181 non-null    object
 3   bodega         186 non-null    object
dtypes: object(4)
memory usage: 5.9+ KB

id_inventario    0
id_producto      6
stock            5
bodega           0
dtype: int64

In [99]:
B_inventario = df.copy()

B_inventario.columns = B_inventario.columns.str.strip().str.lower()

for col in B_inventario.select_dtypes(include='object').columns:
    B_inventario[col] = B_inventario[col].astype(str).str.strip()

    B_inventario = B_inventario.replace(r'^\s*$', pd.NA, regex=True)

    id_producto_vacio = B_inventario['id_producto'].isna() | \
           (B_inventario['id_producto'].astype(str).str.strip() == "") | \
           (B_inventario['id_producto'].astype(str).str.lower() == "nan")

    stock_no_numerico = pd.to_numeric(B_inventario['stock'], errors='coerce').isna()

    B_inventario = B_inventario.drop_duplicates()

In [101]:
validos = B_inventario[
    B_inventario['id_inventario'].notna() &
    B_inventario['id_producto'].notna()&
    B_inventario['stock'].notna() &
    B_inventario['bodega'].notna()
].copy()

In [100]:
rechazados = B_inventario[
     id_producto_vacio|
    stock_no_numerico
].copy()

In [104]:
def motivo(row):

    motivos = []
    valor_id = str(row['id_producto']).strip()
    if pd.isna(row['id_producto']) or valor_id == "" or valor_id.lower() == "nan":
        motivos.append("id_producto_vacio")

    if pd.isna(row['stock']):
        motivos.append("stock_vacio")

    elif pd.to_numeric(row['stock'], errors='coerce') is pd.NA or pd.isna(pd.to_numeric(row['stock'], errors='coerce')):
        motivos.append("stock_no_numerico")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [106]:
rechazados.to_csv("B_inventario_rejects.csv", index=False)
validos.to_csv("B_inventario_curated.csv", index=False)

In [130]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_c7ck_user:kFoJ2P6ViVJGqvzaVHFeHuuMqEThO1y3@dpg-d6qu3vc50q8c73bpda60-a.oregon-postgres.render.com/etl_seguros_c7ck"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [133]:
validos.to_sql(
    'b_inventario_curated',
    engine2,
    if_exists='append',
    index=False
)
rechazados.to_sql(
    'b_inventario_rejects',
    engine2,
    if_exists='append',
    index=False
)

23

In [134]:
pd.read_sql(
"SELECT * FROM b_inventario_curated LIMIT 10",
engine
)

  id_inventario id_producto stock      bodega
0         I7000      PR1115   165    Tránsito
1         I7001      PR1031   236  Sucursal 1
2         I7002      PR1129    40  Sucursal 2
3         I7003      PR1083    61     Central
4         I7004      PR1021   245     Central
5         I7005      PR1026    59     Central
6         I7006      PR1080   124     Central
7         I7007      PR1125   110    Tránsito
8         I7008      PR1091    13     Central
9         I7009      PR1020   247     Central

In [135]:
pd.read_sql(
"SELECT * FROM b_inventario_rejects LIMIT 10",
engine
)

  id_inventario id_producto         stock      bodega     motivo_rechazo
0         I7014         nan           230  Sucursal 2  id_producto_vacio
1         I7019      PR1063           nan  Sucursal 1  stock_no_numerico
2         I7020      PR1024      sin dato    Tránsito  stock_no_numerico
3         I7022      PR1011      sin dato  Sucursal 2  stock_no_numerico
4         I7027      PR1059  203 unidades     Central  stock_no_numerico
5         I7043      PR1125           nan  Sucursal 2  stock_no_numerico
6         I7062      PR1044      sin dato  Sucursal 1  stock_no_numerico
7         I7079      PR1076      sin dato    Tránsito  stock_no_numerico
8         I7092      PR1008           nan  Sucursal 1  stock_no_numerico
9         I7101      PR1061  241 unidades  Sucursal 2  stock_no_numerico